version: '3.9' # not realy needed

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis

  redis:
    image: redis:7
    volumes:
      - redis-data:/data

volumes:
  redis-data: # I asked to add the mapped volume for Redis data persistence in the repository (should be a file mapped to the container)
