version: "3.8"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning", "--dir", "/data"]

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
